from setuptools import setup, find_packages

setup(
    name='audio-slicer',
    version='0.1.0',
    description='A tool for slicing audio files based on silence detection, stolen from https://github.com/openvpi/audio-slicer',
    author='Blaze Burgess',
    # author_email='',
    url='https://github.com/blazeiburgess/audio-slicer',
    packages=find_packages(),
    install_requires=[
        'appdirs==1.4.4',
        'audioread==3.0.1',
        'certifi==2024.6.2',
        'cffi==1.16.0',
        'charset-normalizer==3.3.2',
        'decorator==5.1.1',
        'idna==3.7',
        'importlib_metadata==8.0.0',
        'joblib==1.4.2',
        'lazy_loader==0.4',
        'librosa==0.10.2.post1',
        'llvmlite==0.43.0',
        'msgpack==1.0.8',
        'numba==0.60.0',
        'numpy==1.26.4',
        'packaging==24.1',
        'platformdirs==4.2.2',
        'pooch==1.8.2',
        'pycparser==2.22',
        'pyparsing==3.1.2',
        'requests==2.32.3',
        'resampy==0.4.3',
        'scikit-learn==1.5.0',
        'scipy==1.14.0',
        'soundfile==0.12.1',
        'soxr==0.3.7',
        'threadpoolctl==3.5.0',
        'typing_extensions==4.12.2',
        'urllib3==2.2.2',
        'zipp==3.19.2'
    ],
    entry_points={
        'console_scripts': [
            'audio-slicer=audio_slicer.slicer2:main',
        ],
    },
    classifiers=[
        'Programming Language :: Python :: 3',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
    ],
    python_requires='>=3.6',
)
